### ISSUE TITLE
Bump Arcanist requirement in composer.json

### ISSUE THREAD

**Issue by jamessessford** [laravel-arcanist/inertia-response-renderer#1]
Hey bud,

Could you bump the version requirement for Arcanist to bring in 0.2.0 

Cheers!

**Comment by ksassnowski** [comment]
Whoops, it was still depending on `dev-main` 🙈 Just tagged a 0.2.0 version that uses the correct dependency. Thanks for pointing that out!

**Comment by jamessessford** [comment]
Delighted - thank you :D
